POST http://localhost:10000/book/addBook HTTP/1.1
Content-Type: application/json

{
    "isbn": "0202020",
    "title": "Productivity",
    "author": "Blank",
    "release": "2022-02-02",
    "genre": "Self-help",
    "synopsis": "Some synopsis",
    "photo": "/url.img"
}