########################################
### Books Rest Portion
#########################################

##Get all
GET http://localhost:10000/book/ HTTP/1.1

### Get single Book by ID working
GET http://localhost:10000/book/6424e1c67a3cf725d649558a HTTP/1.1
Content-Type: application/json

###Add Book working
POST http://localhost:10000/book/addBook HTTP/1.1
Content-Type: application/json

{
    "isbn": "123458",
    "title": "Skyward",
    "author": "Brandon Sanderson",
    "release": "2018-06-11",
    "genre": "Sci-Fi",
    "synopsis": "Spensas world has been under alien attack for decades. Pilots are the heroes of whats left of humanity, and becoming a pilot is Spensas dream. Ever since she was a little girl, Spensa has dreamed of soaring skyward and proving her bravery. But her fathers legacy stands in the way—he was a pilot who was killed for desertion years ago, branding Spensa the daughter of a coward, and making her chances of attending flight school slim to none.",
    "photo": "w-o-k.jpg"
}

#### Put Currently not working
PUT http://localhost:10000/book/6424e6987a3cf725d649558c HTTP/1.1
Content-Type: application/json

{
    "isbn": "1234688",
    "title": "Cytonic",
    "author": "Brandon Sanderson",
    "release": "2018-06-11",
    "genre": "Sci-Fi",
    "synopsis": "Spensas world has been under alien attack for 10 decades. Pilots are the heroes of whats left of humanity, and becoming a pilot is Spensas dream. Ever since she was a little girl, Spensa has dreamed of soaring skyward and proving her bravery. But her fathers legacy stands in the way—he was a pilot who was killed for desertion years ago, branding Spensa the daughter of a coward, and making her chances of attending flight school slim to none.",
    "photo": "w-o-k.jpg"
}

### Delete Working
DELETE http://localhost:10000/book/6424e6987a3cf725d649558c HTTP/1.1


#############################
### Reviews Rest Portion
#############################

### Review Get All
GET http://localhost:10000/review/ HTTP/1.1

### Review Get One by ID
GET http://localhost:10000/review/64235ed0780fd2e7c77fcb64 HTTP/1.1

### Review Post
POST http://localhost:10000/review/addReview HTTP/1.1
Content-Type: application/json

{
    "isbn": "0375826696",
    "title": "Eldest (Inheritance, Book 2)",
    "author": "Paolilni, Christopher",
    "image": "eldest.jpg",
    "review_content": "Couldn't have asked for a better sequel. I want more!",
    "rating": "5/5",
    "user": "n-christiansen"
}


### Review Put
PUT http://localhost:10000/review/64235ed0780fd2e7c77fcb64 HTTP/1.1
Content-Type: application/json

{
    "isbn": "0375826696",
    "title": "Eragon (The Inheritance Cycle, Book 1)",
    "author": "Paolilni, Christopher",
    "image": "eragon.jpg",
    "review_content": "This book is the start to something great! This is hands down, one of the best series our there. Once I get started I can never stop. Amazing read.",
    "rating": "5/5",
    "user": "n-christiansen"
}

### Review Delete
DELETE http://localhost:10000/review/ HTTP/1.1